apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: cybv52ppr-go 
  janus-idp.io/tekton: cybv52ppr-go
  backstage.io/kubernetes-id: cybv52ppr-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: cybv52ppr-go
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml